package Test;

import static org.junit.jupiter.api.Assertions.*;

import java.util.HashMap;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import UserManagement.*;
import Products.*;

class TestOrder {
	
	private static HashMap<String,String> customerInfo = new HashMap<String, String>();
	private static HashMap<Product,Integer> myProductList;
	private static Order testOrder;
	private static Eproduct testEproduct;
	private static ClothingProduct testClothing;
	private static Customer testCustomer;
	
	@BeforeAll
	static void setUpBeforeClass() throws Exception {
		// create test product objects
		testCustomer = new Customer("Xin Sun","sxi19@tu-clausthal.de");
		testEproduct = new Eproduct("Iphone15",1000F,100,12,12.5F);
		testClothing = new ClothingProduct("PUMA Tshirt",10F,50,3,"XL","Cotton");
		
		// append customer information into HashMap customerInfo
		customerInfo.put("name",testCustomer.getName());
		customerInfo.put("email", testCustomer.getEmail());
		Integer usID = testCustomer.getUserID();
		customerInfo.put("UserID", usID.toString());
		
		// add products to shopping cart and using generated information create a new order
		testCustomer.addToCart(testEproduct, 10);
		testCustomer.addToCart(testClothing, 10);
		myProductList = testCustomer.calculateTotalTest();
		
		// customerInfo and myProductList are generated by the code upon 
		testOrder = new Order(customerInfo,myProductList);
		
	}

	@Test
	void testGenerateInvoice() {
		// test the function of generateInvoice() and check if the total amount correctly
		testOrder.generateInvoice();
		float result1 = testOrder.getTotalAmount();
		assertEquals(10*10+1000*10,result1);
		
		// generate the same invoice again check if all information and total amount correctly
		testOrder.generateInvoice();
		float result2 = testOrder.getTotalAmount();
		assertEquals(10*10+1000*10,result2);
	}
	
	

}
